### ISSUE TITLE
New file title generation

### ISSUE THREAD

**Issue by a7hybnj2** [mmai/vim-markdown-wiki#4]
Hi, This is awesome! 

I am interested in modifying the content that is auto generated into the new/linked file. I think [this](https://github.com/mmai/vim-markdown-wiki/blob/aba50241ccf987bf0395b9a700f3dce894bf7a16/after/ftplugin/markdown.vim#L195) might be the line I would need to edit. But, I really don't know what is going on here.

I would be interested in including a date/time format to the title and replacing the "======" with a singular # for start of line.

Perhaps have some option flags that can be set for different approaches. :MdwiDateOn, ect.

**Comment by mmai** [comment]
Hi. This is a very good idea, thank you!

I made a new release. You can now customize how the title is rendered, just copy the example of the Readme in your _.vimrc_ and adapt the time format to your taste (there are some examples here : http://vim.wikia.com/wiki/Insert_current_date_or_time).

You could implement the flags like this : 

```vim
function! ToogleTitleDate()
  if exists('g:MdwiDateOn')
    unlet g:MdwiDateOn
  else
    let g:MdwiDateOn='y'
  end
endfunction

function! MdwiWriteTitle(word)
  let strTime = ''
  if exists('g:MdwiDateOn')
    let strTime = strftime('%c').' - '
  end

  return 'normal!\ a# '.strTime.escape(a:word, ' \').'\<esc>'
endfunction
```
and type `:call ToogleTitleDate()` to switch mode.

**Comment by a7hybnj2** [comment]
Sweet!!! I’ll give it a whirl tonight.
